//ToDo: erweitern
var stocks  =  [
    // DAX
    { label: 'Siemens Aktiengesellschaft', value: 'SIE.DE' },
    { label: 'Allianz SE', value: 'ALV.DE' },
    { label: 'Covestro AG', value: '1COV.DE' },
    { label: 'adidas AG', value: 'ADS.DE' },
    { label: 'Wirecard AG', value: 'WDI.DE' },
    { label: 'SAP SE', value: 'SAP.DE' },
    { label: 'Fresenius Medical Care AG & Co. KGaA', value: 'FME.DE' },
    { label: 'Beiersdorf Aktiengesellschaft', value: 'BEI.DE' },
    { label: 'Vonovia SE', value: 'VNA.DE' },
    { label: 'Fresenius SE & Co. KGaA', value: 'FRE.DE' },
    { label: 'Munchener Ruckversicherungs-Gesellschaft Aktiengesellschaft', value: 'MUV2.DE' },
    { label: 'Henkel AG & Co. KGaA', value: 'HEN3.DE' },
    { label: 'Linde plc', value: 'LIN.DE' },
    { label: 'E.ON SE', value: 'EOAN.DE' },
    { label: 'Daimler AG', value: 'DAI.DE' },
    { label: 'Continental Aktiengesellschaft', value: 'CON.DE' },
    { label: 'RWE Aktiengesellschaft', value: 'RWE.DE' },
    { label: 'Infineon Technologies AG', value: 'IFX.DE' },
    { label: 'Volkswagen AG', value: 'VOW3.DE' },
    { label: 'Deutsche Telekom AG', value: 'DTE.DE' },
    { label: 'BASF SE', value: 'BAS.DE' },
    { label: 'Bayerische Motoren Werke Aktiengesellschaft', value: 'BMW.DE' },
    { label: 'thyssenkrupp AG', value: 'TKA.DE' },
    { label: 'MERCK Kommanditgesellschaft auf Aktien', value: 'MRK.DE' },
    { label: 'HeidelbergCement AG', value: 'HEI.DE' },
    { label: 'Deutsche Borse AG', value: 'MRK.DE' },
    { label: 'Deutsche Lufthansa AG', value: 'LHA.DE' },
    { label: 'Deutsche Post AG', value: 'DPW.DE' },
    { label: 'Deutsche Bank Aktiengesellschaft', value: 'DBK.DE' },
    { label: 'Bayer Aktiengesellschaft', value: 'BAYN.DE' },

    { label: 'Microsoft Corp.', value: 'MSFT'},
    { label: 'Apple Inc.', value: 'AAPL'},
    { label: 'Tanger Factory Outlet Centers, Inc.', value: 'SKT'},
    { label: 'Facebook, Inc.', value: 'FB'},
    { label: 'Alphabet, Inc. (GOOG)', value: 'GOOG'},
    { label: 'Alphabet, Inc. (GOOGL)', value: 'GOOGL'},
    { label: 'Royal Dutch Shell plc (RDS-A)', value: 'RDS-A'},
    { label: 'Royal Dutch Shell plc (RDS-B)', value: 'RDS-B'},
    { label: 'Royal Dutch Shell plc (RDSA.AS)', value: 'RDSA.AS'},
    { label: 'Royal Dutch Shell plc (RDSB.L)', value: 'RDSB.L'},
    { label: 'Shell Midstream Partners, L.P. (SHLX)', value: 'SHLX'},
    { label: 'BP p.l.c', value: 'BP'},
    { label: 'The Coca-Cola Company (KO)', value: 'KO'},
    { label: 'Coca-Cola Consolidated, Inc (COKE)', value: 'COKE'},
    { label: 'Coca-Cola European Partners plc (CCEP)', value: 'CCEP'},
    { label: 'Coca-Cola FEMSA, S.A.B. de C.V. (KOF)', value: 'KOF'},
    { label: 'Coca-Cola HBC AG (CCH.L)', value: 'CCH.L'},
    { label: 'The Walt Disney Company (DIS)', value: 'DIS'},
    { label: 'The Walt Disney Company (DISB34.SA)', value: 'DISB34.SA'},
    { label: 'The Walt Disney Company (DISN.BA)', value: 'DISN.BA'},
    { label: 'The Walt Disney Company (DIS.MX)', value: 'DIS.MX'},
    { label: 'DISNEY (WALT) CO. (DIS.D)', value: 'DIS.D'},
    { label: 'Starbucks Corporation', value: 'SBUX'},
    { label: 'Altria Group, Inc. (MO)', value: 'MO'}



];